name: Daily Health Check

on:
  schedule:
    - cron: '0 0 * * *'  # Daily at 12:00 AM UTC
  workflow_dispatch:

jobs:
  health-check:
    runs-on: ubuntu-latest

    steps:
      - name: Print daily message
        run: echo "✅ Daily Flask app health check complete."
